### ISSUE TITLE
How to run for pair end reads on MetaPhlAn 2.0 ?

### ISSUE THREAD

**Issue by kumar2501** [biobakery/biobakery#8]
I want to do analysis on a sample with pair end reads with MetaPhlAn 2.0. Please let me know whether, command allows to run with the same.
Thanks in advance
Jitesh

**Comment by kescobo** [comment]
Hi @kumar2501, you can just pass two files as inputs, separated by a comma

```
metaphlan2.py metagenome_1.fastq,metagenome_2.fastq
```

Alternatively, since metaphlan does not use pairing information to make a profile, you can simply concatenate your read files together.

[See here](https://github.com/biobakery/MetaPhlAn/wiki/MetaPhlAn2#basic-usage), and also check out the [new forums](https://forum.biobakery.org/), which are probably a better place for usage questions.
